package platform

// builtins contains the built-in platform definitions.
var builtins = []Platform{
	{
		ID:                  "claude",
		Name:                "Claude Code",
		ConfigDir:           ".claude",
		TemplateDirs:        []string{"common", "claude"},
		AgentCapable:        true,
		HasHooks:            true,
		SupportsAgentSkills: true,
		CLIFlag:             "--claude",
		Class:               ClassPushBased,
	},
	{
		ID:                  "cursor",
		Name:                "Cursor",
		ConfigDir:           ".cursor",
		TemplateDirs:        []string{"common", "cursor"},
		AgentCapable:        true,
		HasHooks:            true,
		SupportsAgentSkills: true,
		CLIFlag:             "--cursor",
		Class:               ClassPushBased,
	},
	{
		ID:                  "codex",
		Name:                "Codex",
		ConfigDir:           ".codex",
		TemplateDirs:        []string{"common", "codex"},
		AgentCapable:        true,
		HasHooks:            true,
		SupportsAgentSkills: true,
		CLIFlag:             "--codex",
		Class:               ClassPullBased,
	},
	{
		ID:                  "opencode",
		Name:                "OpenCode",
		ConfigDir:           ".opencode",
		TemplateDirs:        []string{"common", "opencode"},
		AgentCapable:        true,
		HasHooks:            true,
		SupportsAgentSkills: true,
		CLIFlag:             "--opencode",
		Class:               ClassPushBased,
	},
	{
		ID:                  "gemini",
		Name:                "Gemini CLI",
		ConfigDir:           ".gemini",
		TemplateDirs:        []string{"common", "gemini"},
		AgentCapable:        true,
		HasHooks:            false,
		SupportsAgentSkills: false,
		CLIFlag:             "--gemini",
		Class:               ClassPullBased,
	},
	{
		ID:                  "kiro",
		Name:                "Kiro",
		ConfigDir:           ".kiro",
		TemplateDirs:        []string{"common", "kiro"},
		AgentCapable:        true,
		HasHooks:            true,
		SupportsAgentSkills: true,
		CLIFlag:             "--kiro",
		Class:               ClassPushBased,
	},
	{
		ID:                  "copilot",
		Name:                "Copilot",
		ConfigDir:           ".github/copilot",
		TemplateDirs:        []string{"common", "copilot"},
		AgentCapable:        false,
		HasHooks:            false,
		SupportsAgentSkills: false,
		CLIFlag:             "--copilot",
		Class:               ClassPullBased,
	},
	{
		ID:                  "devin",
		Name:                "Devin",
		ConfigDir:           ".devin",
		TemplateDirs:        []string{"common", "devin"},
		AgentCapable:        false,
		HasHooks:            false,
		SupportsAgentSkills: false,
		CLIFlag:             "--devin",
		Class:               ClassAgentless,
		Aliases:             []string{"--windsurf"},
	},
	{
		ID:                  "kilo",
		Name:                "Kilo",
		ConfigDir:           ".kilo",
		TemplateDirs:        []string{"common", "kilo"},
		AgentCapable:        false,
		HasHooks:            false,
		SupportsAgentSkills: false,
		CLIFlag:             "--kilo",
		Class:               ClassAgentless,
	},
	{
		ID:                  "pi",
		Name:                "Pi",
		ConfigDir:           ".pi",
		TemplateDirs:        []string{"common", "pi"},
		AgentCapable:        true,
		HasHooks:            true,
		SupportsAgentSkills: true,
		CLIFlag:             "--pi",
		Class:               ClassPushBased,
	},
	{
		ID:                  "codebuddy",
		Name:                "CodeBuddy",
		ConfigDir:           ".codebuddy",
		TemplateDirs:        []string{"common", "codebuddy"},
		AgentCapable:        true,
		HasHooks:            true,
		SupportsAgentSkills: true,
		CLIFlag:             "--codebuddy",
		Class:               ClassPushBased,
	},
	{
		ID:                  "droid",
		Name:                "Droid",
		ConfigDir:           ".droid",
		TemplateDirs:        []string{"common", "droid"},
		AgentCapable:        true,
		HasHooks:            true,
		SupportsAgentSkills: true,
		CLIFlag:             "--droid",
		Class:               ClassPushBased,
	},
	{
		ID:                  "qoder",
		Name:                "Qoder",
		ConfigDir:           ".qoder",
		TemplateDirs:        []string{"common", "qoder"},
		AgentCapable:        true,
		HasHooks:            false,
		SupportsAgentSkills: false,
		CLIFlag:             "--qoder",
		Class:               ClassPullBased,
	},
	{
		ID:                  "antigravity",
		Name:                "Antigravity",
		ConfigDir:           ".antigravity",
		TemplateDirs:        []string{"common", "antigravity"},
		AgentCapable:        false,
		HasHooks:            false,
		SupportsAgentSkills: false,
		CLIFlag:             "--antigravity",
		Class:               ClassAgentless,
	},
	{
		ID:                  "reasonix",
		Name:                "Reasonix",
		ConfigDir:           ".reasonix",
		TemplateDirs:        []string{"common", "reasonix"},
		AgentCapable:        true,
		HasHooks:            true,
		SupportsAgentSkills: true,
		CLIFlag:             "--reasonix",
		Class:               ClassPushBased,
	},
	{
		ID:                  "zcode",
		Name:                "ZCode",
		ConfigDir:           ".zcode",
		TemplateDirs:        []string{"common", "zcode"},
		AgentCapable:        true,
		HasHooks:            true,
		SupportsAgentSkills: true,
		CLIFlag:             "--zcode",
		Class:               ClassPushBased,
	},
}
